# Generated by Django 3.0.7 on 2020-07-21 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20200718_1928'),
        ('analytics', '0002_auto_20200721_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='Kirr_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortener.KirrURL'),
        ),
    ]
